import { NextResponse } from "next/server";
import PocketBase from "pocketbase";

// Use server-side PB instance to ensure admin rights
// In a real app, use strict env vars. Here using the known dev defaults for this environment.
const PB_URL = process.env.NEXT_PUBLIC_PB_URL || "http://127.0.0.1:8091";
const ADMIN_EMAIL = process.env.PB_ADMIN_EMAIL || "root@debug.com";
const ADMIN_PASS = process.env.PB_ADMIN_PASS || "Tongxinyuan2026!";

// Helper to quickly get admin authenticated client
async function getAdminClient() {
    const pb = new PocketBase(PB_URL);
    await pb.admins.authWithPassword(ADMIN_EMAIL, ADMIN_PASS);
    return pb;
}

export async function POST(request: Request) {
    try {
        const pb = await getAdminClient();

        // 1. Create Test Beneficiaries (10)
        const beneficiaries = [];
        for (let i = 1; i <= 10; i++) {
            beneficiaries.push({
                name: `[Test] Beneficiary ${i}`,
                phone: `1380000${String(i).padStart(4, '0')}`,
                id_card: `TESTID${String(i).padStart(4, '0')}`,
                status: 'active'
            });
        }

        // 2. Create Test Volunteers (5)
        const volunteers = [];
        for (let i = 1; i <= 5; i++) {
            volunteers.push({
                name: `[Test] Volunteer ${i}`,
                phone: `1390000${String(i).padStart(4, '0')}`,
                email: `test_vol_${i}@example.com`,
                status: 'pending',
                motivation: 'Generated by Data Seeder'
            });
        }

        // Execute Creations
        // Note: PocketBase doesn't have bulk create API yet, so we map promises.
        // Doing strictly sequential to avoid potentially overwhelming sqlite if locked, 
        // but Promise.all is usually fine for small batch.
        await Promise.all([
            ...beneficiaries.map(d => pb.collection('beneficiaries').create(d)),
            ...volunteers.map(d => pb.collection('volunteer_applications').create(d))
        ]);

        return NextResponse.json({
            success: true,
            message: `Created ${beneficiaries.length} beneficiaries and ${volunteers.length} volunteer applications.`
        });

    } catch (error: any) {
        console.error("Seed Error:", error);
        return NextResponse.json(
            { success: false, error: error.message },
            { status: 500 }
        );
    }
}

export async function DELETE(request: Request) {
    try {
        const pb = await getAdminClient();

        // Find relevant records
        // Filter by name starts with "[Test]"
        // PB Filter: name ~ '[Test]%'
        const beneficiaries = await pb.collection('beneficiaries').getFullList({
            filter: "name ~ '[Test]%'"
        });

        const volunteers = await pb.collection('volunteer_applications').getFullList({
            filter: "name ~ '[Test]%'"
        });

        // Delete them
        const deletions = [
            ...beneficiaries.map(r => pb.collection('beneficiaries').delete(r.id)),
            ...volunteers.map(r => pb.collection('volunteer_applications').delete(r.id))
        ];

        await Promise.all(deletions);

        return NextResponse.json({
            success: true,
            message: `Deleted ${deletions.length} test records.`
        });

    } catch (error: any) {
        console.error("Clear Seed Error:", error);
        return NextResponse.json(
            { success: false, error: error.message },
            { status: 500 }
        );
    }
}
