import { NextResponse } from "next/server";
import PocketBase from "pocketbase";

// Use server-side PB instance to ensure admin rights
const PB_URL = process.env.NEXT_PUBLIC_PB_URL || "http://127.0.0.1:8091";
const ADMIN_EMAIL = process.env.PB_ADMIN_EMAIL || "root@debug.com";
const ADMIN_PASS = process.env.PB_ADMIN_PASS || "Tongxinyuan2026!";

// Helper to quickly get admin authenticated client
async function getAdminClient() {
    const pb = new PocketBase(PB_URL);
    pb.autoCancellation(false); // Disable auto-cancellation for parallel requests
    await pb.admins.authWithPassword(ADMIN_EMAIL, ADMIN_PASS);
    return pb;
}

// Random Data Helpers
const LAST_NAMES = ["张", "王", "李", "赵", "陈", "刘", "杨", "黄", "吴", "周"];
const FIRST_NAMES = ["伟", "芳", "娜", "敏", "静", "强", "磊", "洋", "艳", "杰", "勇", "军"];

function getRandomName() {
    const last = LAST_NAMES[Math.floor(Math.random() * LAST_NAMES.length)];
    const first = FIRST_NAMES[Math.floor(Math.random() * FIRST_NAMES.length)];
    return `[Test] ${last}${first}`;
}

function getRandomPhone() {
    return `13${Math.floor(Math.random() * 10)}${Math.floor(Math.random() * 100000000).toString().padStart(8, '0')}`;
}

function getRandomID() {
    return `TEST${Math.floor(Math.random() * 100000000000000).toString().padStart(14, '0')}`;
}

export async function POST(request: Request) {
    try {
        const pb = await getAdminClient();

        // 1. Create Test Beneficiaries (10)
        const beneficiaries = [];
        for (let i = 1; i <= 10; i++) {
            beneficiaries.push({
                name: getRandomName(),
                phone: getRandomPhone(),
                id_card: getRandomID(),
                status: Math.random() > 0.2 ? 'active' : 'archived', // 80% active
                address: "测试地址 " + Math.floor(Math.random() * 100) + " 号",
                background_note: "此档案为系统自动生成的测试数据。"
            });
        }

        // 2. Create Test Volunteers (5)
        const volunteers = [];
        for (let i = 1; i <= 5; i++) {
            const vName = getRandomName().replace("[Test]", "[Test] 志愿者-");
            volunteers.push({
                name: vName,
                phone: getRandomPhone(),
                email: `val_${Math.floor(Math.random() * 10000)}@test.com`,
                status: Math.random() > 0.5 ? 'approved' : 'pending',
                skills: JSON.stringify(Math.random() > 0.5 ? ["medical", "teaching"] : ["driving"]), // Simple mock skills
                motivation: 'Generated by Data Seeder with random values.'
            });
        }

        // Execute Creations
        await Promise.all([
            ...beneficiaries.map(d => pb.collection('beneficiaries').create(d)),
            ...volunteers.map(d => pb.collection('volunteer_applications').create(d))
        ]);

        return NextResponse.json({
            success: true,
            message: `Created ${beneficiaries.length} beneficiaries and ${volunteers.length} volunteer applications with random data.`
        });

    } catch (error: any) {
        console.error("Seed Error:", error);
        return NextResponse.json(
            { success: false, error: error.message },
            { status: 500 }
        );
    }
}

export async function DELETE(request: Request) {
    try {
        const pb = await getAdminClient();

        // Find relevant records
        const beneficiaries = await pb.collection('beneficiaries').getFullList({
            filter: "name ~ '[Test]%'"
        });

        const volunteers = await pb.collection('volunteer_applications').getFullList({
            filter: "name ~ '[Test]%'"
        });

        // Delete them
        const deletions = [
            ...beneficiaries.map(r => pb.collection('beneficiaries').delete(r.id)),
            ...volunteers.map(r => pb.collection('volunteer_applications').delete(r.id))
        ];

        await Promise.all(deletions);

        return NextResponse.json({
            success: true,
            message: `Deleted ${deletions.length} test records.`
        });

    } catch (error: any) {
        console.error("Clear Seed Error:", error);
        return NextResponse.json(
            { success: false, error: error.message },
            { status: 500 }
        );
    }
}
